### ISSUE TITLE
In relation to multiple sequences within a .fasta file (하나의 .fasta 파일에 복수의 sequence 처리에 관련하여)

### ISSUE THREAD

**Issue by wonyoungtae** [jongseo-park/RoseTTAFold_docker#1]
When I attempted to use RoseTTAFold as I had before, I encountered the following error at the end. Therefore, I wanted to use RoseTTAFold through a different method.

```
$ nano /log/pick.stderr

Traceback (most recent call last):
  File "/home/yt/RoseTTAFold/DAN-msa/pick_final_models.div.py", line 113, in <module>
    pool = mp.Pool(n_core_pool)
  File "/home/yt/anaconda3/envs/folding/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/home/yt/anaconda3/envs/folding/lib/python3.7/multiprocessing/pool.py", line 169, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
```

In this case, if there are multiple sequences in the input.fasta file, for example:
```
$ nano input.fasta

seq_1
ASDDFES..DFY
seq_2
AADGFSDFFS..E
...
seq_n
ADDFGGD..E
```

How should I generate the results? Or should each sequence be placed in a separate .fasta file?

---------------------------------------------------
기존에 RoseTTAFold에서 사용했을 때, 마지막에 다음과 같은 에러 때문에 다른 방법을 통하여 RoseTTAFold를 사용하고자 하였습니다.

```
Traceback (most recent call last):
  File "/home/yt/RoseTTAFold/DAN-msa/pick_final_models.div.py", line 113, in <module>
    pool = mp.Pool(n_core_pool)
  File "/home/yt/anaconda3/envs/folding/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/home/yt/anaconda3/envs/folding/lib/python3.7/multiprocessing/pool.py", line 169, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
```

이 때, input.fasta에 여러 sequence가 있다면, 예를 들어,
```
$ nano input.fasta

>seq_1
ASDDFES..DFY
>seq_2
AADGFSDFFS..E
...
>seq_n
ADDFGGD..E
```

이렇다면 결과를 어떻게 만들어주나요? 아니면 .fasta 파일 당 하나로 만들어야 하나요?

**Comment by jongseo-park** [comment]
안녕하세요

제가 이 repo를 관리한지 너무 오래되어 잘 기억이 안나지만.. 그래도 몇자 말씀드리자면 다음과 같습니다.


RF 의 기본 기능은 monomer 의 구조예측이라서요, 모델링을 위해서는 한 단백질 서열이 포함된 아미노산 서열을 fasta 에 넣어야 합니다.

여러 단백질의 모델링을 위해서는 각각 만든 fasta 파일을 개별적으로 실행시켜 결과를 얻어야 합니다.

```
>seq_1
ASDDFES..DFY
```

```
>seq_2
AADGFSDFFS..E
```

.... 이런식으로요




단순 구조 모델링이 필요하신 경우라면 

colabfold (https://github.com/sokrypton/ColabFold) 를 사용해보세요.

alphafold, rosettafold 모두 지원합니다.

**Comment by wonyoungtae** [comment]
늦은 저녁에 답변감사합니다.

최근 연구 진행 중에 많은 sequence를 모두 활용해야 하는 경우가 발생했습니다. 이에 제공해주신 docker를 활용했을 때, 역시
github에 말씀드렸던 에러가 계속하여 발생하였습니다. 혹시 이에 대해 해결책을 아시는 부분이 있으신지 궁금합니다.

그리고 말씀해주신 colabfold도 한번 같이 활용해보도록 하겠습니다.

감사합니다.


2023년 9월 18일 (월) 오후 10:48, jongseo ***@***.***>님이 작성:

**Comment by jongseo-park** [comment]
안녕하세요

여러개의 native 단백질 구조 모델링의 경우 
https://alphafold.ebi.ac.uk
에서 검색해서 손쉽게 구조를 얻을 수 있습니다.

만일 갖고계신 서열이 native 단백질의 서열이 아니라면, 아무래도 colabfold 를 활용하시는게 가장 빠를 듯하고요

Colabfold 를 로컬에서 돌릴 수 있는 localcolabfold 를 사용하시는것도 좋으리라 생각됩니다.

**Comment by wonyoungtae** [comment]
Great!  자세한 답변을 제공해주셔서 감사합니다. 좋은 하루 되세요!

원영태 올림

2023년 9월 25일 (월) 오전 1:34, jongseo ***@***.***>님이 작성:
